# Generated by Django 4.2.3 on 2023-08-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('article_number', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_part_photos', verbose_name='Фотография')),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='interface.carpart', verbose_name='Запчасть')),
            ],
        ),
    ]
