# Generated by Django 4.2.3 on 2023-08-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(default='', verbose_name='URL фотографии'),
        ),
    ]
