# Generated by Django 4.2.3 on 2023-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_remove_photo_image_photo_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='place',
            field=models.CharField(default='', max_length=50, verbose_name='Место'),
        ),
    ]
