# Generated by Django 4.2.3 on 2023-08-10 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_carpart_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='added_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
