# Generated by Django 4.2.3 on 2023-08-11 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_matchingarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingarticle',
            name='added_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
