# Generated by Django 4.2.3 on 2023-08-22 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_matchingarticle_added_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50, unique=True)),
                ('added_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
